import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';

import apiUtils from '../../global/utils/api';

import {
  handleCreateFulfilled
  , handleFetchSinglePending
  , handleFetchSingleFulfilled
  , handleFetchSingleRejected
  , handleFetchListPending
  , handleFetchListFulfilled
  , handleFetchListRejected
  , handleMutationPending
  , handleMutationFulfilled
  , handleMutationRejected
  , handleDeletePending
  , handleDeleteFulfilled
  , handleDeleteRejected
  , shouldFetch
  , INITIAL_STATE
  , handleInvalidateQuery
  , handleInvalidateQueries
  , handleAddSingleToList
} from '../../global/utils/storeUtils';


// First define all API calls for __camelName__
/**
 * The functions below, called thunks, allow us to perform async logic. They
 * can be dispatched like a regular action: `dispatch(incrementAsync(10))`. This
 * will call the thunk with the `dispatch` function as the first argument. Async
 * code can then be executed and other actions can be dispatched. Thunks are
 * typically used to make async requests.
 * 
 * In practice we won't dispatch these directly, they will be dispatched by __camelName__Service which has a nicer api built on hooks.
 */

// CREATE
export const sendCreate__PascalName__ = createAsyncThunk(
  '__camelName__/sendCreate'
  , async (new__PascalName__) => {
    const endpoint = `/api/__kebabNamePlural__`;
    const response = await apiUtils.callAPI(endpoint, 'POST', new__PascalName__);
    // The value we return becomes the `fulfilled` action payload
    return response;
  }
);

// READ
export const fetchSingle__PascalName__ = createAsyncThunk(
  '__camelName__/fetchSingle'
  , async (id) => {
    const endpoint = `/api/__kebabNamePlural__/${id}`;
    const response = await apiUtils.callAPI(endpoint);
    // The value we return becomes the `fulfilled` action payload
    return response;
  }
);
export const fetch__PascalName__List = createAsyncThunk(
  '__camelName__/fetchList' // this is the action name that will show up in the console logger.
  , async (listArgs) => {
    const endpoint = `/api/__kebabNamePlural__?${listArgs}`;
    const response = await apiUtils.callAPI(endpoint);
    // The value we return becomes the `fulfilled` action payload
    return response;
  }
);

// UPDATE
export const sendUpdate__PascalName__ = createAsyncThunk(
  '__camelName__/sendUpdate'
  , async ({ _id, ...updates }) => {
    const endpoint = `/api/__kebabNamePlural__/${_id}`;
    const response = await apiUtils.callAPI(endpoint, 'PUT', updates);
    // The value we return becomes the `fulfilled` action payload
    return response;
  }
);

// DELETE
export const sendDelete__PascalName__ = createAsyncThunk(
  '__camelName__/sendDelete'
  , async (id) => {
    const endpoint = `/api/__kebabNamePlural__/${id}`;
    const response = await apiUtils.callAPI(endpoint, 'DELETE');
    // The value we return becomes the `fulfilled` action payload
    return response;
  }
);

// next define the store's initial state, all of our store utils rely on a specific state shape, so use the constant
const initialState = { ...INITIAL_STATE };

// define the __camelName__Slice. This is a combination of actions and reducers. More info: https://redux-toolkit.js.org/api/createSlice
export const __camelName__Slice = createSlice({
  name: '__camelName__'
  , initialState
  /**
   * The `reducers` field lets us define reducers and generate associated actions.
   * Unlike the selectors defined at the bottom of this file, reducers only have access
   * to this specific reducer and not the entire store.
   * 
   * Again, we will not dispatch these directly, they will be dispatched by __camelName__Service.
   */
  , reducers: {
    invalidateQuery: handleInvalidateQuery
    , invalidateQueries: handleInvalidateQueries
    , add__PascalName__ToList: handleAddSingleToList
  }

  /**
   * The `extraReducers` field lets the slice handle actions defined elsewhere,
   * including actions generated by createAsyncThunk or in other slices.
   * We'll use them to track our server request status.
   * 
   * We'll add a case for each API call defined at the top of the file to dictate
   * what happens during each API call lifecycle.
   */
  , extraReducers: (builder) => {
    builder
      // CREATE
      .addCase(sendCreate__PascalName__.fulfilled, handleCreateFulfilled)

      // READ
      .addCase(fetchSingle__PascalName__.pending, handleFetchSinglePending)
      .addCase(fetchSingle__PascalName__.fulfilled, handleFetchSingleFulfilled)
      .addCase(fetchSingle__PascalName__.rejected, handleFetchSingleRejected)
      .addCase(fetch__PascalName__List.pending, handleFetchListPending)
      // because lists are returned from the server named for their resource, we need to pass a `listKey` so the util can properly handle the response
      .addCase(fetch__PascalName__List.fulfilled, (state, action) => handleFetchListFulfilled(state, action, '__camelName__s'))
      .addCase(fetch__PascalName__List.rejected, handleFetchListRejected)

      // UPDATE
      .addCase(sendUpdate__PascalName__.pending, handleMutationPending)
      .addCase(sendUpdate__PascalName__.fulfilled, handleMutationFulfilled)
      .addCase(sendUpdate__PascalName__.rejected, handleMutationRejected)
      // .addCase(sendUpdate__PascalName__.fulfilled, (state, action) => handleMutationFulfilled(state, action, (newState, action) => {
      //   // by passing this optional callback we now have access to the new state if we want to do something else with it, this works for all reducer handlers
      // }))

      // DELETE
      .addCase(sendDelete__PascalName__.pending, handleDeletePending)
      .addCase(sendDelete__PascalName__.fulfilled, handleDeleteFulfilled)
      .addCase(sendDelete__PascalName__.rejected, handleDeleteRejected)
  }
});

// export the actions for the reducers defined above
export const { invalidateQuery, invalidateQueries, add__PascalName__ToList } = __camelName__Slice.actions;


// We can also write thunks by hand, which may contain both sync and async logic.
// Here's an example of conditionally dispatching actions based on current state.

export const fetchListIfNeeded = (queryKey) => (dispatch, getState) => {
  const __camelName__Query = getState().__camelName__.listQueries[queryKey];
  if(shouldFetch(__camelName__Query)) {
    // console.log('Fetching __camelName__ list', queryKey);
    dispatch(fetch__PascalName__List(queryKey));
  } else {
    // console.log('No need to fetch, fresh query in cache');
  }
};

export const fetchSingleIfNeeded = (id) => (dispatch, getState) => {
  const __camelName__Query = getState().__camelName__.singleQueries[id];
  if(shouldFetch(__camelName__Query)) {
    dispatch(fetchSingle__PascalName__(id));
  } else {
    // console.log('No need to fetch, fresh query in cache');
  }
}

export default __camelName__Slice.reducer;
